update NPM dep versions
theforeman/npm2rpm pull request #45
Opened 2018-06-21 17:14 UTC by jessp01

2018-06-22 13:46 UTC, ekohl requested changes

2018-06-22 13:46 UTC, ekohl commented on package.json
> +    "tar": "~4.4.4",
It looks like the API changed:
```
$ ./bin/npm2rpm.js -n patternfly-react -s single -v 2.10.1
---- npm2rpm ----
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
 - Starting npm module download: https://registry.npmjs.org/patternfly-react/-/patternfly-react-2.10.1.tgz
 - Unpacking in /tmp/npm2rpm-26409vV0eZwLIIro4 ...
/home/ekohl/dev/npm2rpm/lib/npm_helpers.js:21
  var write_stream = tar.Extract({path: tmpDir, strip: 0})
                         ^

TypeError: tar.Extract is not a function
    at Object.module.exports.extractTar (/home/ekohl/dev/npm2rpm/lib/npm_helpers.js:21:26)
    at Object.<anonymous> (/home/ekohl/dev/npm2rpm/bin/npm2rpm.js:40:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

2018-06-22 13:46 UTC, ekohl commented on package.json
> +    "semver": "^5.5.0",
This change isn't needed. We work with `^5.4.1` and that allows the same max versions as `^5.5.0`.

2018-06-22 18:31 UTC, jessp01 commented
Hi @ekohl,

You're absolutely right about the `tar` NPM. Sorry, I failed to test again after upgrading to the latest, my apologies. I reverted the version and will submit a separate pull to support the newer version.
I also reverted the semver to an earlier version as you requested but can you please explain why you object to upgrading to latest?

Really, the most important thing about this pull is the upgrade of the `request` module as it depends on the `hoek` module in which an exploit was recently reported and fixed:
https://nvd.nist.gov/vuln/detail/CVE-2018-3728

If I'm honest, that's not critical in the case of something like `npm2rpm` but still best to upgrade:)

2018-06-22 18:52 UTC, ekohl commented
@jessp01 generally I prefer open dependencies. I think there are a few more where we now use `~` instead of `^`. That would allow using a much wider range of versions including those with fixed vulnerabilities. If they properly follow semver then it should still work API-wise while allowing the security updates. An example of this is our semver dependency: it allows installing the latest 5.x but we're very wide in which versions we allow.

2018-06-22 18:54 UTC, ekohl commented
Could you also add `package-lock.json` to `.gitignore` btw?

2018-06-22 18:58 UTC, jessp01 commented
@ekohl, semver - understood. package-lock.json added to .gitignore.

2018-10-03 13:11 UTC, ekohl commented
Fixed in https://github.com/dLobatog/npm2rpm/pull/48

2018-10-03 13:11 UTC, closed without merging